apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sapp
  template:
    metadata:
      labels:
        app: k8sapp
    spec:
      containers:
        - name: k8sapp
          image: k8sapp:v1
          ports:
            - containerPort: 5000
