apiVersion: v1
kind: Service
metadata:
  name: k8sapp-service
  namespace: default
spec:
  selector:
    app: k8sapp
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000